apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: yhq64ughs-nodejs
  janus-idp.io/tekton: yhq64ughs-nodejs
  backstage.io/kubernetes-id: yhq64ughs-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: yhq64ughs-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
