apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: yhq64ughs-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: yhq64ughs-nodejs 
  name: yhq64ughs-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: yhq64ughs-nodejs 
